name = "aoc"
version = "0.1.0"
description = "Advent of Code 2024"
licences = ["MIT"]
repository = { type = "github", user = "typesafe", repo = "https://github.com/typesafe/advent-of-code-2024" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
